DockerUtil.go
closed:  devtron-labs/devtron#308
closed: devtron-labs/devtron#141
=> Docker hub supprt

Dockerfile, GitCliUtil.go, GitUtil.go, git-ask-pass.sh
Fixes: devtron-labs/devtron#453
=> Azure support

App.go, DockerUtil.go
Related PR:
https://github.com/devtron-labs/devtron/pull/750
Issues fixed:
https://github.com/devtron-labs/devtron/issues/720
https://github.com/devtron-labs/devtron/issues/721
=> FEATURE: Docker connection option added

App.go
Updated following variables in the list of system env variables needed at the time of script execution - 
1. HOME
=> Update env variables passing in ci-script execution

pubsub/NatsClient.go
logging type changed from Fatal to Println
=> Nats client logging

go.mod, go.sum, helper/ArtefactUploadHelper.go, helper/CacheHelper.go, vendor/github.com/devtron-labs/common-lib/blob-storage/AwsS3Blob.go, vendor/github.com/devtron-labs/common-lib/blob-storage/Bean.go, vendor/modules.txt
Handling is done for cases where versioning is not enabled at minIO buckets.
=> Minio versioning handling

Dockerfile
Updated Dockerfile for multi-arch build
=> Updated Dockerfile for multi-arch build

helper/CacheHelper.go, helper/EventHelper.go, scriptExecutor.go
1) Renaming docker pull cache property name (from invalidateCache to ignoreDockerCachePull)
2) Introducing a new property ignoreDockerCachePush
3) network host added in pre ci step
=> docker cache push pull configurable

App.go, helper/EventHelper.go
deployment release counter param exposed through env vars.
Fixes: https://github.com/devtron-labs/devtron/issues/2569
=> deployment release counter Exposed as Env Vars

App.go, Dockerfile, buildpack.json, helper/CacheHelper.go, helper/CommandExecutor_test.go, helper/DockerHelper.go, helper/EventHelper.go, util/CommonConstants.go
Fixes: devtron-labs/devtron/issues/2561
=> Build Project using Buildpack or sample Dockerfile templates

App.go, StageExecutor.go, helper/EventHelper.go
Fixes: [2875](https://github.com/devtron-labs/devtron/issues/2875)
=> fix: empty map and build skip handling added

App.go, helper/GitCliHelper.go
Adding GIT_MATERIAL_REQUEST point as it will be needed for Semgrep scan. GIT_MATERIAL_REQUEST will be of form "<repo_name>,<checkout_path>,<branch_name>,<commit_hash>"
=> feat: semgrep plugin changes

helper/CacheHelper.go, helper/DockerHelper.go, helper/EventHelper.go, util/CommonConstants.go
For shorted build time, PVC has been added in pods at app level and pipeline level
=> fix: pvc mounted on pods for cache handling

App.go, helper/EventHelper.go, util/CommonConstants.go
1. setting extra environment variables came in request in ci
2. added buildStatus env variable in post-ci
=> feat: setting extra environment variables came in request in ci

App.go, go.sum, helper/EventHelper.go
Show the timer/counter metrics for kube-link api using Prometheus.
Fixes #https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2216
Github issue: #https://github.com/devtron-labs/devtron/issues/3022
=> feat: Add timer/counter telemetry for CI process

App.go, go.mod, go.sum, helper/ArtefactUploadHelper.go, helper/DockerHelper.go, helper/EventHelper.go, vendor/github.com/devtron-labs/common-lib/blob-storage/BlobStorageService.go, vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go, vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go, vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go, vendor/modules.txt
Added a check on isArtifactUploaded to and sent nates event to orchestrator for the same
fixes: https://github.com/devtron-labs/devtron/issues/3122
=> feat: job feature ci runner

helper/DockerHelper.go
The image being used for multi-platform shows error of docker hub pull rate limits, updated the image with quay
=> fix: Updated dockerhub image with quay

App.go
This PR fixes https://github.com/devtron-labs/devtron/issues/3278
=> fix: Create a Dockerfile does not work if Dockerfile is present in repository 

App.go, StageExecutor_test.go, helper/DockerHelper.go, helper/EventHelper.go
Retry for Image Push
https://github.com/devtron-labs/devtron/issues/3432
=> Retry for Image Push

envUtils.go
strings.Cut is introduced with go 1.18, updated
=> replaced strings.Cut with strings.splitN

helper/DockerHelper.go
driver-opt arg should be wrapped in '' quotes to use multiple nodeselector or tolerations
Fixes #
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
```release-note
```
=> fix: commandd fix for multiple nodeselectors and tolerations

helper/DockerHelper.go
Fixes https://github.com/devtron-labs/devtron/issues/3809
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
```release-note
```
=> fix: creating buildx dir before setting up cache or building command

App.go, helper/DockerHelper.go, helper/DockerHelper_test.go, helper/EventHelper.go, util/CommonConstants.go
Fixes #3918 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
```release-note
```
=> feat: enhanced buildx w.r.t target platforms

helper/ExpressionEvaluater.go, helper/pluginBean.go
PASS condition is not working as expected 
Fixes #3554
All tests are performed locally.
```release-note
```
=> fix: Pass/Failure Condition is not working as expected in pre build step.

helper/DockerHelper.go
https://github.com/devtron-labs/devtron/issues/4080
=> fix: K8s driver unique pod name

cdStages.go, helper/EventHelper.go
[4177](https://github.com/devtron-labs/devtron/issues)
=> enhancement: skip checkout for ci-job type cd stages

helper/DockerHelper.go, helper/EventHelper.go
https://github.com/devtron-labs/devtron/issues/4291
=> fix: updating docker login command

helper/DockerHelper.go, util/CommonConstants.go
related to : devtron-labs/devtron#719
=> fix: increased wait time

app/AppHelper.go, executor/stage/ciStages.go, executor/util/envUtils.go, helper/StageTypeHelper.go, util/CommonConstants.go
Updated event type for JOBS. Previously it was being handled through type CI only.
=> chore: refactoring for event type 

go.mod, go.sum, vendor/golang.org/x/net/http/httpproxy/proxy.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/pipe.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/testsync.go, vendor/golang.org/x/net/http2/transport.go, vendor/modules.txt
Updated the versions for depenadbot security. 
Fixes #
=> chore: dependabot version upgrade

executor/stage/ciStages.go, helper/EventHelper.go
issue - https://github.com/devtron-labs/devtron/issues/5515
=> rename TempCommitDetails to CiProjectDetailsMin

executor/StageExecutor.go, executor/scriptExecutor.go, executor/stage/ciStages.go, helper/DockerHelper.go
This pr handles the case when a user uses runtime params in case of external CI, and gives in custom image, but not image digest , then we will be fetching digest using docker pull  command,
=> Hotfix v0.15.0

.github/semantic.yml
=> chore: OSS main branch sync 
